import { readFileSync } from "node:fs";
import { LEAVES } from "./catalogue.js";

// PACK-01: single source for generated release records. The committed
// skills/mg-axi/SKILL.md command table and docs/coverage.md are projections
// of the executable catalogue and the discovery inventory, so help, skill
// and coverage cannot drift apart. tools/generate-docs.mjs writes both
// files; test/pack.test.mjs fails when they are stale.

// One row per executable leaf in catalogue order.
// Every leaf is implemented by an mg-axi handler (native). Graph
// leaves carry the read effect, except reviewed named writes.
function leafEffect(leaf: { path: string; operation?: string }): string {
  if (leaf.operation !== undefined) return leaf.operation.startsWith("GET:") ? "read" : "write";
  return leaf.path === "api get" || leaf.path === "doctor" ? "read" : "local";
}
export function skillCommandTable(): string {
  return [
    "| Command | Capability | Effect |",
    "|---|---|---|",
    ...LEAVES.map(leaf => `| \`mg-axi ${leaf.path}\` | native | ${leafEffect(leaf)} |`),
  ].join("\n");
}

type InventoryRow = {
  id: string;
  disposition: string;
  owningSlice: string | null;
  reason: string;
};

// Initial write families resolve to shipped when the catalogue carries a
// leaf for one of their v1.0 operations, and stay pending while every row
// remains unimplemented. Family membership comes from the inventory
// owningSlice and shipped status comes from the catalogue, so a merged
// write slice flips its own row without touching this template. Blocked,
// deprecated and unavailable variants never count as pending.
function initialWriteStatus(rows: InventoryRow[]): { shipped: string[]; pending: string[] } {
  const families = new Map<string, string[]>();
  for (const row of rows) {
    const operation = /^v1\.0:(.+)$/.exec(row.id)?.[1];
    if (operation === undefined || row.owningSlice === null || !/^WRITE-0[1-9]$/.test(row.owningSlice)) continue;
    if (row.disposition === "intentionally-blocked" || row.disposition === "deprecated" || row.disposition === "unavailable") continue;
    families.set(row.owningSlice, [...(families.get(row.owningSlice) ?? []), operation]);
  }
  const shipped: string[] = [];
  const pending: string[] = [];
  for (const [slice, operations] of [...families.entries()].sort()) {
    const leaf = LEAVES.find(candidate => candidate.operation !== undefined && operations.includes(candidate.operation));
    if (leaf) shipped.push(`${slice} (\`mg-axi ${leaf.path}\`)`);
    else pending.push(`${slice} (${operations.map(operation => `\`${operation}\``).join(", ")})`);
  }
  return { shipped, pending };
}

const DISPOSITIONS = ["named-command", "reviewed-raw-read", "scheduled", "intentionally-blocked", "deprecated", "unavailable", "excluded"] as const;

// The capability report is generated from the catalogue: every executable
// read leaf owns one row with its inventory disposition and owning slice,
// and the counts separate implemented leaves from inventory dispositions.
// Scheduled work never counts as complete and excluded rows stay separate
// from scoped capabilities, per docs/inventory.md. There is no completeness
// percentage: the report names the supported Entra read surface, not full
// Entra coverage.
export function capabilityDocument(): string {
  const inventory = JSON.parse(readFileSync(new URL("../inventory/operations.json", import.meta.url), "utf8")) as {
    operations: InventoryRow[];
  };
  const rows = inventory.operations;
  const count = (disposition: string): number => rows.filter(row => row.disposition === disposition).length;
  const writeStatus = initialWriteStatus(rows);
  const readLeaves = LEAVES.filter(leaf => leaf.operation !== undefined && leaf.operation.startsWith("GET:"));
  const writeLeaves = LEAVES.filter(leaf => leaf.operation !== undefined && !leaf.operation.startsWith("GET:"));
  const commandRows = readLeaves.map(leaf => {
    const row = rows.find(candidate => candidate.id === `v1.0:${leaf.operation}`);
    return `| \`mg-axi ${leaf.path}\` | \`${leaf.operation}\` | ${row ? row.disposition : "no v1.0 inventory row"} | ${row?.owningSlice ?? "-"} |`;
  });
  const writeRows = writeLeaves.map(leaf => {
    const row = rows.find(candidate => candidate.id === `v1.0:${leaf.operation}`);
    return `| \`mg-axi ${leaf.path}\` | \`${leaf.operation}\` | ${row?.owningSlice ?? "-"} |`;
  });
  const deferredDomainRows = rows.filter(row => row.owningSlice === "EXT-01" && row.reason.startsWith("Deferred by firstmate R1 "));
  const deferredProviderRows = rows.filter(row => row.owningSlice === "EXT-03" && row.reason.startsWith("Deferred to a later EXT-03 "));
  const readCount = readLeaves.length + 2;
  const localCount = LEAVES.length - readCount - writeLeaves.length;
  return [
    "<!-- Generated by tools/generate-docs.mjs from src/catalogue.ts and inventory/operations.json. Do not hand-edit. -->",
    "",
    "# mg-axi coverage",
    "",
    "This is the supported Entra read surface, not full Entra coverage.",
    "Only the commands below have an implemented, tested leaf; every other",
    "operation remains scheduled, blocked, deprecated or excluded until its own slice ships.",
    "Inventory dispositions are discovery-time records from INV-01; the command",
    "list below is the implemented truth and never counts scheduled work as complete.",
    "",
    "## Counts",
    "",
    `- implemented read leaves: ${readCount} (${readLeaves.length} named Entra reads plus reviewed raw api get and doctor health check)`,
    `- implemented write leaves: ${writeLeaves.length} (named gated mutations below)`,
    `- local leaves: ${localCount} (home, profile, login and setup views)`,
    ...DISPOSITIONS.map(disposition => `- inventory ${disposition}: ${count(disposition)}`),
    "",
    "## Commands",
    "",
    "| Command | Operation | Inventory (v1.0) | Owning slice |",
    "|---|---|---|---|",
    ...commandRows,
    "| `mg-axi api get` | reviewed raw reads (see src/api.ts) | reviewed-raw-read catalogue | API-01 |",
    "| `mg-axi doctor` | bounded `GET:/users` health check | uses the named user-list read | PACK-01 |",
    "",
    "## EXT-01 domain scope decisions",
    "",
    "Firstmate decision R1: approve narrowing this change to the eight v1.0 domain reads above.",
    "The operations below remain scheduled with an explicit deferred disposition to a later EXT-01 subfamily; no new commands or raw access are approved.",
    "Federation stays out because it can carry signing-certificate material.",
    "Firstmate decision R2: keep the write-family status section as the coverage fix added to scope (resolved-kept).",
    "Both firstmate decisions must also be stated in the PR body by the delivery phase.",
    "",
    "| Inventory operation | Disposition | Owning slice | Deferral reason |",
    "|---|---|---|---|",
    ...deferredDomainRows.map(row => `| \`${row.id}\` | ${row.disposition} (deferred) | ${row.owningSlice} | ${row.reason} |`),
    "",
    "## EXT-03 identity-provider scope decisions",
    "",
    "This change covers the four v1.0 workforce identity-provider reads above (list, show, count, available-types).",
    "The four beta operations below remain scheduled with an explicit deferred disposition to a later EXT-03 subfamily.",
    "Identity-provider reads support v1.0 only; beta needs its own review.",
    "Workforce context only; no external-customer (B2C/External ID tenant) support is claimed.",
    "",
    "| Inventory operation | Disposition | Owning slice | Deferral reason |",
    "|---|---|---|---|",
    ...deferredProviderRows.map(row => `| \`${row.id}\` | ${row.disposition} (deferred) | ${row.owningSlice} | ${row.reason} |`),
    "",
    "## Named writes",
    "",
    "Each write below runs the WRITE-00 mutation coordinator: hand-enabled profile, immutable scope, preview, explicit `--execute`, typed target confirmation for disruptive effects, durable journal intent/outcome and no replay. Inventory dispositions stay discovery-time records until a metadata refresh reviews them; the implemented review lives beside each command.",
    "",
    "| Command | Operation | Owning slice |",
    "|---|---|---|",
    ...writeRows,
    "",
    `Shipped initial writes: ${writeStatus.shipped.length ? writeStatus.shipped.join(", ") : "none"}.`,
    `Pending initial writes: ${writeStatus.pending.length ? writeStatus.pending.join(", ") : "none"}.`,
    "Extended families (EXT-01 through EXT-04) and the full-Entra audit (FULL-01, COMPLETE-01) own the remaining",
    "scheduled rows; see docs/build-plan.md for their dispatch.",
    "",
  ].join("\n");
}
