import { readFileSync } from "node:fs";
import { LEAVES } from "./catalogue.js";

// PACK-01: single source for generated release records. The committed
// skills/mg-axi/SKILL.md command table and docs/coverage.md are projections
// of the executable catalogue and the discovery inventory, so help, skill
// and coverage cannot drift apart. tools/generate-docs.mjs writes both
// files; test/pack.test.mjs fails when they are stale.

// One row per executable leaf in catalogue order, matching the home-view
// help. Every leaf is implemented by an mg-axi handler (native). Graph
// leaves carry the read effect; help, profile, setup and doctor views stay
// local and offline.
export function skillCommandTable(): string {
  return [
    "| Command | Capability | Effect |",
    "|---|---|---|",
    ...LEAVES.map(leaf => `| \`mg-axi ${leaf.path}\` | native | ${leaf.operation !== undefined || leaf.path === "api get" ? "read" : "local"} |`),
  ].join("\n");
}

type InventoryRow = {
  id: string;
  disposition: string;
  owningSlice: string | null;
};

const DISPOSITIONS = ["named-command", "reviewed-raw-read", "scheduled", "intentionally-blocked", "deprecated", "unavailable", "excluded"] as const;

// The capability report is generated from the catalogue: every executable
// read leaf owns one row with its inventory disposition and owning slice,
// and the counts separate implemented leaves from inventory dispositions.
// Scheduled work never counts as complete and excluded rows stay separate
// from scoped capabilities, per docs/inventory.md. There is no completeness
// percentage: the report names the supported Entra read surface, not full
// Entra coverage.
export function capabilityDocument(): string {
  const inventory = JSON.parse(readFileSync(new URL("../inventory/operations.json", import.meta.url), "utf8")) as {
    operations: InventoryRow[];
  };
  const rows = inventory.operations;
  const count = (disposition: string): number => rows.filter(row => row.disposition === disposition).length;
  const readLeaves = LEAVES.filter(leaf => leaf.operation !== undefined);
  const commandRows = readLeaves.map(leaf => {
    const row = rows.find(candidate => candidate.id === `v1.0:${leaf.operation}`);
    return `| \`mg-axi ${leaf.path}\` | \`${leaf.operation}\` | ${row ? row.disposition : "no v1.0 inventory row"} | ${row?.owningSlice ?? "-"} |`;
  });
  const readCount = readLeaves.length + 1;
  const localCount = LEAVES.length - readLeaves.length - 1;
  return [
    "<!-- Generated by tools/generate-docs.mjs from src/catalogue.ts and inventory/operations.json. Do not hand-edit. -->",
    "",
    "# mg-axi coverage",
    "",
    "This is the supported Entra read surface, not full Entra coverage.",
    "Only the commands below have an implemented, tested leaf; every other",
    "operation remains scheduled, blocked, deprecated or excluded until its own slice ships.",
    "Inventory dispositions are discovery-time records from INV-01; the command",
    "list below is the implemented truth and never counts scheduled work as complete.",
    "",
    "## Counts",
    "",
    `- implemented read leaves: ${readCount} (${readLeaves.length} named Entra reads plus reviewed raw api get)`,
    `- local leaves: ${localCount} (home, profile, login, setup and doctor views)`,
    ...DISPOSITIONS.map(disposition => `- inventory ${disposition}: ${count(disposition)}`),
    "",
    "## Commands",
    "",
    "| Command | Operation | Inventory (v1.0) | Owning slice |",
    "|---|---|---|---|",
    ...commandRows,
    "| `mg-axi api get` | reviewed raw reads (see src/api.ts) | reviewed-raw-read catalogue | API-01 |",
    "",
    "Extended families (EXT-01 through EXT-04), later writes (WRITE-00 and",
    "beyond) and the full-Entra audit (FULL-01, COMPLETE-01) own the remaining",
    "scheduled rows; see docs/build-plan.md for their dispatch.",
    "",
  ].join("\n");
}
